name: Validate Sigma rules

"on":
  push:
    paths:
      - 'detections/sigma/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'detections/sigma/**'
  workflow_dispatch:

jobs:
  sigma-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sigma-cli
        run: |
          pipx install sigma-cli
          pipx inject sigma-cli pysigma-backend-splunk

      - name: Validate rules
        run: |
          sigma check detections/sigma/
